export const fieldNames = {
  address: [
    "address",
    "address1",
    "streetaddress",
    "residence",
    "place",
    "addressstreet1",
    "location",
  ],
  attach_file: ["attachfile", "attachresume"],
  city: [
    "city",
    "addresslevel2",
    "addresssectioncity",
    "town",
    "municipality",
    "level2",
  ],
  company: ["company", "employer"],
  company_location: ["location"],
  currently_work_here: ["currentlyworkhere"],
  collage: ["school", "university", "institute"],
  country: ["country", "countryid", "nation"],

  degree: ["degree"],
  disability_status: ["disabilitystatus", "disability"],
  dob: ["dateofbirth", "dob", "birthdate", "birth"],
  education_button: ["education", "school", "collage", "college", "university"],
  email_address: [
    "email",
    "jobapplication[email]",
    "jobapplicationemail",
    "emailaddress",
    "emailaddressverify",
    "primaryemail",
    "retypeemail",
  ],

  full_name: ["fullname", "signature"],
  first_name: [
    "firstname",
    "givenname",
    "fname",
    "guestfirstname",
    "guestFirstName",
  ],
  file: ["file"],
  field_of_study: ["study", "field"],
  gpa: ["gpa", "result"],
  gender: ["gender", "sex"],
  github: ["git", "github"],
  hispanic_latino: ["hispanic", "latino"],

  is_over_18: ["age"],
  job_title: ["jobtitle", "title", "job"],
  last_name: ["lastname", "familyname", "lname"],
  language: ["language"],
  middle_name: ["middlename", "mname"],
  month: ["month"],
  major: ["major", "department"],
  name: ["name", "signature"],

  linkedin_url: [
    "urls[linkedin]",
    "urlsLinkedin",
    "linkedinurl",
    "linkedin",
    // "profile",
    // "jobapplication",
    // "website",
  ],

  phone_number: [
    "phone",
    "contact",
    "phonenumberall",
    "number",
    "mobile",
    "mobilenumber",
    "tel",
    "telephone",
  ],
  phone_number_text: [
    "phone",
    "contact",
    "phonenumberall",
    "number",
    "mobile",
    "mobilenumber",
    "telephone",
    "cellular ",
  ],
  phone_type: ["phonetype", "devicetype", "phone", "device"],
  race: ["race", "ethnicity"],
  role_description: ["roledescription", "description", "role"],

  salary: ["salary", "pay"],
  started_date: [""],
  state: ["state", "province", "territory"],
  salary_expectations: ["salary_expectation", "salary_expectations"],

  terms_and_condation: [
    "agreementCheckbox",
    "termsandconditions",
    "terms",
    "conditions",
    "accept",
    "agree",
  ],

  us_work_authorization: ["legallyauthorized"],
  veteran: ["veteran"],
  veteran_status: [" veteranstatus", " veteran"],
  visa: ["sponsorship", "visa"],
  work_experience: ["experience", "work", "employment", "working"],
  workday_country: ["addressSection_regionSubdivision1"],

  year: ["year"],
  zip_code: ["zip", "zipcode", "postalcode", "postal", "postcode"],
  portfolio: ["website", "portfolio"],
};
