export const fieldNames = {
  full_name: ["fullname"],
  first_name: [
    "firstname",
    "givenname",
    "fname",
    "guestfirstname",
    "guestFirstName",
  ],
  middle_name: ["middlename", "mname"],
  last_name: ["lastname", "familyname", "lname"],
  email_address: [
    "email",
    "jobapplication[email]",
    "jobapplicationemail",
    "emailaddress",
    "emailaddressverify",
    "primaryemail",
    "retypeemail",
  ],
  phone_number: [
    "phone",
    "contact",
    "phonenumberall",
    "number",
    "mobile",
    "mobilenumber",
    "tel",
    "telephone",
  ],
  phone_number_text: [
    "phone",
    "contact",
    "phonenumberall",
    "number",
    "mobile",
    "mobilenumber",
    "telephone",
  ],
  address: [
    "address",
    "address1",
    "streetaddress",
    "residence",
    "place",
    "addressstreet1",
  ],
  city: [
    "city",
    "addresslevel2",
    "addresssectioncity",
    "town",
    "municipality",
    "level2",
  ],
  state: ["state"],
  country: ["country", "countryid", "nation"],
  workday_country: ["addressSection_regionSubdivision1"],
  zip_code: ["zip", "zipcode", "postalcode", "postal", "postcode"],
  salary_expectations: ["salary_expectation", "salary_expectations"],
  linkedin_url: [
    "urls[linkedin]",
    "urlsLinkedin",
    "linkedinurl",
    "linkedin",
    // "profile",
    // "jobapplication",
    // "website",
  ],
  file: ["file"],
  education_button: ["education", "school", "collage", "college", "university"],
  work_experience: ["experience", "work", "employment", "working"],
  role_description: ["roledescription", "description", "role"],
  job_title: ["jobtitle", "title", "job"],
  company: ["company", "employer"],
  company_location: ["location"],
  currently_work_here: ["currentlyworkhere"],
  collage: ["school", "university"],
  degree: ["degree"],
  started_date: [""],
  month: ["month"],
  year: ["year"],
  is_over_18: ["age"],
  gender: ["gender"],
  disability_status: ["disabilitystatus", "disability"],
  veteran_status: [" veteranstatus", " veteran"],
  race: ["race"],
};
